[pytest]
markers =
    countries: tests for the Country resource
    leagues: tests for the League resource
    teams: tests for the Team resource
    players: tests for the Player resource
    matches: tests for the Match resource
    user: tests for the User/auth resource