# CREATE : IDK HOW TO CHECK DUPLICATES HERE TBH, BUT I WILL THINK ABOUT IT WHEN I DO IT
# UPDATE : CHECK IF THE COUNTRY THEY ARE SETTING, EXISTS OR NOT, BETTER, GIVE THEM A SCROLLABLE LIST TO PICK FROM, DONT GIVE THEM OPTIONS TO SEND 
# DELETE : DELETING MATCHES SHOULDN'T BE DELETING TEAMS OR LEAGUES