# CREATE : NAME AND LONG NAME, CHECK THEM IG?
# UPDATE : CHECK ID TO AVOID COUNTING SAME THING TWICE FOR UNIQUE VALS AND EVERYTHING IS KINDA OPTIONAL, FIX THE SCHEMAS FIRST!
# DELETE : IF TEAM GETS DELETED, PLAYERS SHOULDN'T GET DELETED! BUT TEAM ATTRIBUTES SHOULD GET DELETED! -> CAN BE ARCHIVED, LIKE WE SEND A NEW PROPERTY WITH RESPONSE : ARCHIVED as status
# like we did for pagination response : 
#  class PaginationResponse(BaseModel, Generic[T]):
    # total: int
    # skip: int
    # limit: int
    # items: list[T]

# TEAM ATTRIBUTES:
    # CREATE : WHILE CREATING, IT'S BEST IF WE CAN SHOW A SCROLLING ELEMENT TO CHOOSE TEAMS FROM, INSTEAD OF SENDING A ID
    # UPDATE : SAME LIKE OTHERS, JUST BE CAREFUL ABOUT DUPS
    # DELETE : DELETING A TEAM ATTRIBUTES SHOULDN'T DELETE TEAMS!
