"""made prefered_foot, attacking and defensive work rate optional

Revision ID: 1e6427e2776c
Revises: dfe707a2f183
Create Date: 2026-09-12 14:57:15.493799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6427e2776c'
down_revision: Union[str, Sequence[str], None] = 'dfe707a2f183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_attributes', 'preferred_foot',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('player_attributes', 'attacking_work_rate',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('player_attributes', 'defensive_work_rate',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_attributes', 'defensive_work_rate',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('player_attributes', 'attacking_work_rate',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('player_attributes', 'preferred_foot',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
