"""Restricted deletion of some foreignkeys which are required

Revision ID: 27e6d77425eb
Revises: f034650e96e1
Create Date: 2026-09-24 12:41:27.397876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e6d77425eb'
down_revision: Union[str, Sequence[str], None] = 'f034650e96e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('leagues_country_id_fkey'), 'leagues', type_='foreignkey')
    op.create_foreign_key(None, 'leagues', 'countries', ['country_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('matches', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint(op.f('matches_away_team_id_fkey'), 'matches', type_='foreignkey')
    op.drop_constraint(op.f('matches_league_id_fkey'), 'matches', type_='foreignkey')
    op.drop_constraint(op.f('matches_country_id_fkey'), 'matches', type_='foreignkey')
    op.drop_constraint(op.f('matches_home_team_id_fkey'), 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'countries', ['country_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'matches', 'teams', ['home_team_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'matches', 'teams', ['away_team_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'matches', 'leagues', ['league_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key(op.f('matches_home_team_id_fkey'), 'matches', 'teams', ['home_team_id'], ['id'])
    op.create_foreign_key(op.f('matches_country_id_fkey'), 'matches', 'countries', ['country_id'], ['id'])
    op.create_foreign_key(op.f('matches_league_id_fkey'), 'matches', 'leagues', ['league_id'], ['id'])
    op.create_foreign_key(op.f('matches_away_team_id_fkey'), 'matches', 'teams', ['away_team_id'], ['id'])
    op.alter_column('matches', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint(None, 'leagues', type_='foreignkey')
    op.create_foreign_key(op.f('leagues_country_id_fkey'), 'leagues', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###
