"""add remaining models

Revision ID: 2df5fe41b8f6
Revises: dc03b937738b
Create Date: 2026-09-08 13:03:52.098544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df5fe41b8f6'
down_revision: Union[str, Sequence[str], None] = 'dc03b937738b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_api_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('player_fifa_api_id', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_api_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_api_id', sa.Integer(), nullable=False),
    sa.Column('team_fifa_api_id', sa.Float(), nullable=True),
    sa.Column('team_long_name', sa.String(), nullable=True),
    sa.Column('team_short_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_api_id')
    )
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_country_id'), 'leagues', ['country_id'], unique=False)
    op.create_table('player_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_fifa_api_id', sa.Integer(), nullable=False),
    sa.Column('player_api_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('overall_rating', sa.Float(), nullable=True),
    sa.Column('potential', sa.Float(), nullable=True),
    sa.Column('preferred_foot', sa.String(), nullable=False),
    sa.Column('attacking_work_rate', sa.String(), nullable=False),
    sa.Column('defensive_work_rate', sa.String(), nullable=False),
    sa.Column('sprint_speed', sa.Float(), nullable=True),
    sa.Column('finishing', sa.Float(), nullable=True),
    sa.Column('short_passing', sa.Float(), nullable=True),
    sa.Column('dribbling', sa.Float(), nullable=True),
    sa.Column('standing_tackle', sa.Float(), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('gk_diving', sa.Float(), nullable=True),
    sa.Column('gk_handling', sa.Float(), nullable=True),
    sa.Column('gk_kicking', sa.Float(), nullable=True),
    sa.Column('gk_positioning', sa.Float(), nullable=True),
    sa.Column('gk_reflexes', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_api_id'], ['players.player_api_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_attributes_player_api_id'), 'player_attributes', ['player_api_id'], unique=False)
    op.create_table('team_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_fifa_api_id', sa.Integer(), nullable=True),
    sa.Column('team_api_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('buildUpPlaySpeed', sa.Integer(), nullable=True),
    sa.Column('buildUpPlayDribbling', sa.Integer(), nullable=True),
    sa.Column('buildUpPlayPassing', sa.Integer(), nullable=True),
    sa.Column('buildUpPlayPositioningClass', sa.String(), nullable=True),
    sa.Column('chanceCreationPassing', sa.Integer(), nullable=True),
    sa.Column('chanceCreationCrossing', sa.Integer(), nullable=True),
    sa.Column('chanceCreationShooting', sa.Integer(), nullable=True),
    sa.Column('chanceCreationPositioningClass', sa.String(), nullable=True),
    sa.Column('defencePressure', sa.Integer(), nullable=True),
    sa.Column('defenceAggression', sa.Integer(), nullable=True),
    sa.Column('defenceTeamWidth', sa.Integer(), nullable=True),
    sa.Column('defenceDefenderLineClass', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_api_id'], ['teams.team_api_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_attributes_team_api_id'), 'team_attributes', ['team_api_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('match_api_id', sa.Integer(), nullable=True),
    sa.Column('home_team_api_id', sa.Integer(), nullable=False),
    sa.Column('away_team_api_id', sa.Integer(), nullable=False),
    sa.Column('home_team_goal', sa.Integer(), nullable=True),
    sa.Column('away_team_goal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_api_id'], ['teams.team_api_id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['home_team_api_id'], ['teams.team_api_id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_country_id'), 'matches', ['country_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_country_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_team_attributes_team_api_id'), table_name='team_attributes')
    op.drop_table('team_attributes')
    op.drop_index(op.f('ix_player_attributes_player_api_id'), table_name='player_attributes')
    op.drop_table('player_attributes')
    op.drop_index(op.f('ix_leagues_country_id'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_table('teams')
    op.drop_table('players')
    op.drop_table('countries')
    # ### end Alembic commands ###
