"""point FKs at internal id columns, drop fifa_api_id fields

Revision ID: bd1b832f840e
Revises: 1e6427e2776c
Create Date: 2026-09-17 15:47:30.057053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd1b832f840e'
down_revision: Union[str, Sequence[str], None] = '1e6427e2776c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('home_team_id', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('away_team_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_matches_home_team_id'), 'matches', ['home_team_id'], unique=False)
    op.drop_constraint(op.f('matches_away_team_api_id_fkey'), 'matches', type_='foreignkey')
    op.drop_constraint(op.f('matches_home_team_api_id_fkey'), 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'teams', ['home_team_id'], ['id'])
    op.create_foreign_key(None, 'matches', 'teams', ['away_team_id'], ['id'])
    op.drop_column('matches', 'home_team_api_id')
    op.drop_column('matches', 'away_team_api_id')
    op.add_column('player_attributes', sa.Column('player_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_player_attributes_player_api_id'), table_name='player_attributes')
    op.create_index(op.f('ix_player_attributes_player_id'), 'player_attributes', ['player_id'], unique=False)
    op.drop_constraint(op.f('player_attributes_player_api_id_fkey'), 'player_attributes', type_='foreignkey')
    op.create_foreign_key(None, 'player_attributes', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    op.drop_column('player_attributes', 'player_fifa_api_id')
    op.drop_column('player_attributes', 'player_api_id')
    op.drop_column('players', 'player_fifa_api_id')
    op.add_column('team_attributes', sa.Column('team_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_team_attributes_team_api_id'), table_name='team_attributes')
    op.create_index(op.f('ix_team_attributes_team_id'), 'team_attributes', ['team_id'], unique=False)
    op.drop_constraint(op.f('team_attributes_team_api_id_fkey'), 'team_attributes', type_='foreignkey')
    op.create_foreign_key(None, 'team_attributes', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_column('team_attributes', 'team_api_id')
    op.drop_column('team_attributes', 'team_fifa_api_id')
    op.drop_constraint(op.f('teams_team_api_id_key'), 'teams', type_='unique')
    op.create_index(op.f('ix_teams_team_api_id'), 'teams', ['team_api_id'], unique=True)
    op.drop_column('teams', 'team_fifa_api_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('team_fifa_api_id', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_teams_team_api_id'), table_name='teams')
    op.create_unique_constraint(op.f('teams_team_api_id_key'), 'teams', ['team_api_id'], postgresql_nulls_not_distinct=False)
    op.add_column('team_attributes', sa.Column('team_fifa_api_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('team_attributes', sa.Column('team_api_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'team_attributes', type_='foreignkey')
    op.create_foreign_key(op.f('team_attributes_team_api_id_fkey'), 'team_attributes', 'teams', ['team_api_id'], ['team_api_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_team_attributes_team_id'), table_name='team_attributes')
    op.create_index(op.f('ix_team_attributes_team_api_id'), 'team_attributes', ['team_api_id'], unique=False)
    op.drop_column('team_attributes', 'team_id')
    op.add_column('players', sa.Column('player_fifa_api_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player_attributes', sa.Column('player_api_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('player_attributes', sa.Column('player_fifa_api_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'player_attributes', type_='foreignkey')
    op.create_foreign_key(op.f('player_attributes_player_api_id_fkey'), 'player_attributes', 'players', ['player_api_id'], ['player_api_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_player_attributes_player_id'), table_name='player_attributes')
    op.create_index(op.f('ix_player_attributes_player_api_id'), 'player_attributes', ['player_api_id'], unique=False)
    op.drop_column('player_attributes', 'player_id')
    op.add_column('matches', sa.Column('away_team_api_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('matches', sa.Column('home_team_api_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key(op.f('matches_home_team_api_id_fkey'), 'matches', 'teams', ['home_team_api_id'], ['team_api_id'])
    op.create_foreign_key(op.f('matches_away_team_api_id_fkey'), 'matches', 'teams', ['away_team_api_id'], ['team_api_id'])
    op.drop_index(op.f('ix_matches_home_team_id'), table_name='matches')
    op.drop_column('matches', 'away_team_id')
    op.drop_column('matches', 'home_team_id')
    # ### end Alembic commands ###
