"""added slugs on Players & Teams tables

Revision ID: dfe707a2f183
Revises: a9be7761e12f
Create Date: 2026-09-12 13:22:35.949373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe707a2f183'
down_revision: Union[str, Sequence[str], None] = 'a9be7761e12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('slug', sa.String(), nullable=False))
    op.create_index(op.f('ix_players_slug'), 'players', ['slug'], unique=True)
    op.add_column('teams', sa.Column('slug', sa.String(), nullable=False))
    op.create_index(op.f('ix_teams_slug'), 'teams', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_slug'), table_name='teams')
    op.drop_column('teams', 'slug')
    op.drop_index(op.f('ix_players_slug'), table_name='players')
    op.drop_column('players', 'slug')
    # ### end Alembic commands ###
